global:
  resolve_timeout: 5m

route:
  receiver: 'slack_notifications'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

  routes:
    - match:
        severity: 'critical'
      receiver: 'email_notifications'
      continue: true

receivers:
  - name: 'slack_notifications'
    slack_configs:
      - api_url: 'Incoming webhooks url'
        channel: '#prometheus'
        send_resolved: true

  - name: 'email_notifications'
    email_configs:
      - to: 'example@gmail.com'
        from: 'sender@gmail.com'
        smarthost: 'smtp.host.com:587'
        auth_username: 'sender@gmail.com'
        auth_password: 'password'
        send_resolved: true
